import {
  GarpMQuestionTemplate,
  garpMQuestionSafetyBoundary,
  yesNoUnsureOptions,
} from "@/lib/garpM/questionTemplateModel";

export const diagnosisSymptomsTreatmentQuestions: GarpMQuestionTemplate[] = [
  {
    id: "dst_condition_name",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "condition_name",
    questionText: "What condition are you preparing information about?",
    helperText:
      "Use the name you normally use for the condition. This can be updated later if a doctor uses different wording.",
    answerType: "TEXT",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 10,
    evidenceCategory: "DIAGNOSIS",
    summaryLabel: "Condition name",
    validationRules: [
      {
        type: "MIN_LENGTH",
        value: 2,
        message: "Enter at least a short condition name.",
      },
    ],
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_diagnosis_status",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "diagnosis_status",
    questionText: "Has this condition been diagnosed by a doctor or specialist?",
    helperText:
      "This helps separate diagnosed, provisional, self-reported and uncertain information before evidence is organised.",
    answerType: "SINGLE_SELECT",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 20,
    evidenceCategory: "DIAGNOSIS",
    summaryLabel: "Diagnosis status",
    options: [
      { value: "DIAGNOSED", label: "Diagnosed" },
      { value: "PROVISIONAL_DIAGNOSIS", label: "Provisional diagnosis" },
      { value: "SELF_REPORTED", label: "Self-reported symptoms only" },
      { value: "NOT_YET_DIAGNOSED", label: "Not yet diagnosed" },
      { value: "UNSURE", label: "Unsure" },
    ],
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_diagnosis_date",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "diagnosis_date",
    questionText: "When was the condition diagnosed, if known?",
    helperText:
      "An approximate date is useful if known. Leave blank if you are unsure.",
    answerType: "DATE",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 30,
    evidenceCategory: "DIAGNOSIS",
    summaryLabel: "Diagnosis date",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_main_symptoms",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "main_symptoms",
    questionText: "What are the main symptoms you currently experience?",
    helperText:
      "Describe symptoms in plain English. Include what happens, how it feels, and any common triggers.",
    answerType: "LONG_TEXT",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 40,
    evidenceCategory: "SYMPTOMS",
    summaryLabel: "Main symptoms",
    validationRules: [
      {
        type: "MIN_LENGTH",
        value: 10,
        message: "Add a short plain-English description of the symptoms.",
      },
    ],
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_symptom_frequency",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "symptom_frequency",
    questionText: "How often do the symptoms occur?",
    helperText:
      "This helps organise whether symptoms are constant, daily, frequent, occasional or flare-up based.",
    answerType: "SINGLE_SELECT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 50,
    evidenceCategory: "SYMPTOMS",
    summaryLabel: "Symptom frequency",
    options: [
      { value: "CONSTANT", label: "Constant or nearly constant" },
      { value: "DAILY", label: "Daily" },
      { value: "MOST_DAYS", label: "Most days" },
      { value: "WEEKLY", label: "Weekly" },
      { value: "OCCASIONAL", label: "Occasional" },
      { value: "FLARE_UPS_ONLY", label: "During flare-ups only" },
      { value: "UNSURE", label: "Unsure" },
    ],
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_symptom_severity_examples",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "symptom_severity_examples",
    questionText: "What does a bad day or flare-up look like?",
    helperText:
      "Give practical examples. This is useful for explaining impact without trying to calculate a score.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 60,
    evidenceCategory: "SYMPTOMS",
    summaryLabel: "Bad day or flare-up examples",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_current_treatment",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "current_treatment",
    questionText: "What treatment or support are you currently receiving?",
    helperText:
      "Include GP care, specialists, allied health, counselling, physiotherapy, hearing support, pain management or other treatment.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 70,
    evidenceCategory: "TREATMENT",
    summaryLabel: "Current treatment",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_medications",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "medications",
    questionText: "Are you taking medication for this condition?",
    helperText:
      "List medication names if known. Do not change medication based on this app. Speak with a doctor or pharmacist.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 80,
    evidenceCategory: "MEDICATION",
    summaryLabel: "Medication",
    safetyNote:
      "Do not start, stop or change medication based on this app. Speak with a doctor, pharmacist or qualified clinician.",
  },
  {
    id: "dst_medication_side_effects",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "medication_side_effects",
    questionText: "Do you experience side effects from medication or treatment?",
    helperText:
      "Only record what you experience. This app does not provide medication advice.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 90,
    evidenceCategory: "MEDICATION",
    summaryLabel: "Medication or treatment side effects",
    options: yesNoUnsureOptions,
    safetyNote:
      "Medication concerns should be discussed with a doctor, pharmacist or qualified clinician.",
  },
  {
    id: "dst_side_effect_details",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "side_effect_details",
    questionText: "If yes, what side effects or treatment problems do you notice?",
    helperText:
      "Describe the side effects, when they happen, and how they affect daily life.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 100,
    evidenceCategory: "MEDICATION",
    summaryLabel: "Side effect details",
    safetyNote:
      "Medication concerns should be discussed with a doctor, pharmacist or qualified clinician.",
  },
  {
    id: "dst_relevant_reports",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "relevant_reports",
    questionText: "What diagnosis, treatment or medical reports do you already have?",
    helperText:
      "Examples include GP summaries, specialist reports, imaging reports, hearing tests, medication lists or treatment plans.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 110,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Available medical evidence",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "dst_missing_reports",
    groupKey: "DIAGNOSIS_SYMPTOMS_TREATMENT",
    questionKey: "missing_reports",
    questionText: "What diagnosis, treatment or medical evidence may still be missing?",
    helperText:
      "This helps prepare appointment questions and evidence gap prompts.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 120,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Missing medical evidence",
    safetyNote: garpMQuestionSafetyBoundary,
  },
];