import {
  GarpMQuestionTemplate,
  garpMQuestionSafetyBoundary,
  yesNoUnsureOptions,
} from "@/lib/garpM/questionTemplateModel";

const evidenceCategoryOptions = [
  { value: "DIAGNOSIS", label: "Diagnosis evidence" },
  { value: "SYMPTOMS", label: "Symptoms evidence" },
  { value: "TREATMENT", label: "Treatment evidence" },
  { value: "MEDICATION", label: "Medication evidence" },
  { value: "FUNCTIONAL_IMPACT", label: "Functional impact evidence" },
  { value: "LIFESTYLE_IMPACT", label: "Lifestyle impact evidence" },
  { value: "WORK_IMPACT", label: "Work impact evidence" },
  { value: "WORSENING", label: "Worsening evidence" },
  { value: "PREVIOUS_COMPENSATION", label: "Previous DVA or compensation evidence" },
  { value: "SERVICE_CONNECTION", label: "Service connection notes" },
  { value: "APPOINTMENT_PREP", label: "Appointment preparation notes" },
];

export const evidenceAppointmentPrepQuestions: GarpMQuestionTemplate[] = [
  {
    id: "eap_existing_evidence_summary",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "existing_evidence_summary",
    questionText: "What evidence do you already have for this condition?",
    helperText:
      "List documents, reports, notes or records you already have. Examples include GP reports, specialist reports, DVA letters, treatment notes, medication lists, imaging, hearing tests, personal notes or support letters.",
    answerType: "LONG_TEXT",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 10,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Existing evidence",
    validationRules: [
      {
        type: "MIN_LENGTH",
        value: 5,
        message: "Add a short description of existing evidence, or write that you do not have any yet.",
      },
    ],
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "eap_missing_evidence_summary",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "missing_evidence_summary",
    questionText: "What evidence do you think is still missing?",
    helperText:
      "List anything that may need to be requested, located or discussed. This is a preparation prompt only and does not say what DVA will require.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 20,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Missing evidence",
    safetyNote:
      "This app does not decide what evidence DVA will require. It only helps organise possible gaps for discussion with a doctor, advocate, lawyer or support person.",
  },
  {
    id: "eap_evidence_categories_missing",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "evidence_categories_missing",
    questionText: "Which evidence categories may need more work?",
    helperText:
      "Tick any areas that may need more information, documents or discussion.",
    answerType: "MULTI_SELECT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 30,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Evidence categories needing work",
    options: evidenceCategoryOptions,
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "eap_documents_to_request",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "documents_to_request",
    questionText: "What documents do you need to request or locate?",
    helperText:
      "Examples include GP records, specialist reports, DVA decision letters, previous assessment letters, medication history, treatment plans, imaging, test results or employer records.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 40,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Documents to request",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "eap_document_sources",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "document_sources",
    questionText: "Who might hold the missing documents?",
    helperText:
      "Examples include a GP clinic, specialist, hospital, allied health provider, employer, DVA, Open Arms, service records, or personal files.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 50,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Possible document sources",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "eap_doctor_report_needed",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "doctor_report_needed",
    questionText: "Do you need to ask a doctor for a report, summary or clarification?",
    helperText:
      "Choose the closest answer. This can help prepare appointment questions.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 60,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Doctor report or clarification needed",
    options: yesNoUnsureOptions,
    safetyNote:
      "This app does not tell a doctor what to write. It helps the user prepare questions and organise information for discussion.",
  },
  {
    id: "eap_questions_for_doctor",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "questions_for_doctor",
    questionText: "What questions should you ask your doctor at the next appointment?",
    helperText:
      "Examples include diagnosis confirmation, current symptoms, treatment history, medication side effects, stability, functional impact, worsening, or whether records can be provided.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 70,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Questions for doctor",
    safetyNote:
      "This is appointment preparation only. It does not provide medical advice or replace a clinical assessment.",
  },
  {
    id: "eap_questions_for_advocate_or_lawyer",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "questions_for_advocate_or_lawyer",
    questionText: "What questions should you ask an advocate, lawyer or support person?",
    helperText:
      "Examples include pathway questions, missing DVA letters, previous decisions, evidence organisation, timeframes, forms or next steps.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 80,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Questions for advocate, lawyer or support person",
    safetyNote:
      "This app does not provide legal advice. Use this prompt to prepare questions for a qualified person or support service.",
  },
  {
    id: "eap_appointment_notes",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "appointment_notes",
    questionText: "What notes do you want to take into the appointment?",
    helperText:
      "Write short reminders about symptoms, treatment, impact, worsening, missing evidence or documents to request.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 90,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Appointment notes",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "eap_follow_up_actions",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "follow_up_actions",
    questionText: "What follow-up actions should happen after the appointment?",
    helperText:
      "Examples include requesting records, uploading evidence, booking another appointment, asking for a report, updating notes, or speaking with an advocate or lawyer.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 100,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Follow-up actions",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "eap_upload_priority",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "upload_priority",
    questionText: "Which evidence should be uploaded or organised first?",
    helperText:
      "List the highest priority items. This helps prepare the evidence metadata and upload steps.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 110,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Evidence upload priority",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "eap_user_confidence",
    groupKey: "EVIDENCE_APPOINTMENT_PREP",
    questionKey: "user_confidence",
    questionText: "How confident are you that the evidence picture is clear?",
    helperText:
      "This is not a legal or medical assessment. It helps identify whether the user feels ready or needs more help organising information.",
    answerType: "SINGLE_SELECT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 120,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "User confidence in evidence picture",
    options: [
      { value: "CONFIDENT", label: "Confident" },
      { value: "SOMEWHAT_CONFIDENT", label: "Somewhat confident" },
      { value: "NOT_CONFIDENT", label: "Not confident" },
      { value: "UNSURE", label: "Unsure" },
    ],
    safetyNote:
      "This confidence prompt is for preparation only. It does not predict a DVA outcome.",
  },
];