import {
  GarpMQuestionTemplate,
  garpMQuestionSafetyBoundary,
  impactFrequencyOptions,
  yesNoUnsureOptions,
} from "@/lib/garpM/questionTemplateModel";

export const functionalLifestyleWorkImpactQuestions: GarpMQuestionTemplate[] = [
  {
    id: "flw_daily_activity_impact",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "daily_activity_impact",
    questionText: "How does this condition affect ordinary daily activities?",
    helperText:
      "Describe practical examples such as housework, shopping, cooking, driving, appointments, exercise, hobbies or managing routines.",
    answerType: "LONG_TEXT",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 10,
    evidenceCategory: "FUNCTIONAL_IMPACT",
    summaryLabel: "Daily activity impact",
    validationRules: [
      {
        type: "MIN_LENGTH",
        value: 10,
        message: "Add at least one practical daily activity example.",
      },
    ],
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_impact_frequency",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "impact_frequency",
    questionText: "How often does this impact happen?",
    helperText:
      "Choose the closest option. This helps organise whether the impact is daily, frequent, occasional or mainly during flare-ups.",
    answerType: "SINGLE_SELECT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 20,
    evidenceCategory: "FUNCTIONAL_IMPACT",
    summaryLabel: "Impact frequency",
    options: impactFrequencyOptions,
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_self_care_impact",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "self_care_impact",
    questionText: "Does the condition affect self-care or personal routines?",
    helperText:
      "Examples include washing, dressing, grooming, preparing for the day, medication routines, eating, fatigue management or needing extra time.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 30,
    evidenceCategory: "FUNCTIONAL_IMPACT",
    summaryLabel: "Self-care impact",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_mobility_physical_impact",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "mobility_physical_impact",
    questionText: "Does the condition affect movement, physical tasks or getting around?",
    helperText:
      "Describe walking, standing, sitting, lifting, bending, stairs, driving, public transport, balance, falls, pain, fatigue or other limits.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 40,
    evidenceCategory: "FUNCTIONAL_IMPACT",
    summaryLabel: "Mobility and physical impact",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_sleep_impact",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "sleep_impact",
    questionText: "Does the condition affect sleep or rest?",
    helperText:
      "Describe trouble falling asleep, waking during the night, nightmares, pain, tinnitus, medication effects, fatigue or needing naps.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 50,
    evidenceCategory: "LIFESTYLE_IMPACT",
    summaryLabel: "Sleep impact",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_relationship_social_impact",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "relationship_social_impact",
    questionText: "Does the condition affect relationships, family life or social participation?",
    helperText:
      "Describe impacts on family, friends, social events, communication, mood, irritability, avoidance, isolation or needing support.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 60,
    evidenceCategory: "LIFESTYLE_IMPACT",
    summaryLabel: "Relationship and social impact",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_work_impact",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "work_impact",
    questionText: "Does the condition affect work, study or volunteering?",
    helperText:
      "Describe missed work, reduced hours, modified duties, concentration, physical limits, fatigue, pain, stress, performance, reliability or needing support.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 70,
    evidenceCategory: "WORK_IMPACT",
    summaryLabel: "Work, study or volunteering impact",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_work_adjustments",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "work_adjustments",
    questionText: "Have you needed changes or adjustments at work, study or volunteering?",
    helperText:
      "Examples include changed duties, extra breaks, reduced hours, working from home, avoiding tasks, using aids, taking leave or stopping work.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 80,
    evidenceCategory: "WORK_IMPACT",
    summaryLabel: "Work adjustments",
    options: yesNoUnsureOptions,
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_support_needed",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "support_needed",
    questionText: "Do you need help from another person, aids, reminders or routines because of this condition?",
    helperText:
      "Describe help from family, friends, carers, colleagues, reminders, apps, mobility aids, hearing aids, braces, equipment or routines.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 90,
    evidenceCategory: "FUNCTIONAL_IMPACT",
    summaryLabel: "Support needed",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_good_day_bad_day",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "good_day_bad_day",
    questionText: "What is the difference between a better day and a worse day?",
    helperText:
      "This helps capture variation without trying to calculate a score. Give practical examples of what changes.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 100,
    evidenceCategory: "FUNCTIONAL_IMPACT",
    summaryLabel: "Better day and worse day examples",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_impact_evidence_available",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "impact_evidence_available",
    questionText: "What evidence or notes show this functional, lifestyle or work impact?",
    helperText:
      "Examples include personal notes, doctor reports, allied health records, employer records, leave records, support letters or appointment notes.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 110,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Impact evidence available",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "flw_impact_questions_for_doctor",
    groupKey: "FUNCTIONAL_LIFESTYLE_WORK_IMPACT",
    questionKey: "impact_questions_for_doctor",
    questionText: "What questions should you ask your doctor about functional, lifestyle or work impact?",
    helperText:
      "Write down anything you want your doctor to clarify, confirm or document at the next appointment.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 120,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Doctor questions about impact",
    safetyNote: garpMQuestionSafetyBoundary,
  },
];