import {
  GarpMQuestionTemplate,
  garpMQuestionSafetyBoundary,
  stabilityOptions,
  yesNoUnsureOptions,
} from "@/lib/garpM/questionTemplateModel";

export const stabilityTreatmentResponseQuestions: GarpMQuestionTemplate[] = [
  {
    id: "str_current_stability",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "current_stability",
    questionText: "How would you describe the current stability of this condition?",
    helperText:
      "Choose the closest option. This helps organise whether the condition is stable, improving, worsening or changing over time.",
    answerType: "SINGLE_SELECT",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 10,
    evidenceCategory: "STABILITY",
    summaryLabel: "Current stability",
    options: stabilityOptions,
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "str_stability_explanation",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "stability_explanation",
    questionText: "Why did you choose that stability option?",
    helperText:
      "Describe what has changed, what has stayed the same, and whether symptoms come and go.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 20,
    evidenceCategory: "STABILITY",
    summaryLabel: "Stability explanation",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "str_symptom_pattern",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "symptom_pattern",
    questionText: "Do symptoms follow a pattern?",
    helperText:
      "Examples include morning symptoms, night symptoms, flare-ups, symptoms after activity, symptoms under stress, or symptoms that vary without a clear trigger.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 30,
    evidenceCategory: "SYMPTOMS",
    summaryLabel: "Symptom pattern",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "str_treatment_helping",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "treatment_helping",
    questionText: "Is current treatment helping?",
    helperText:
      "This helps capture whether treatment is improving symptoms, partly helping, not helping, or making things difficult.",
    answerType: "SINGLE_SELECT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 40,
    evidenceCategory: "TREATMENT",
    summaryLabel: "Treatment response",
    options: [
      { value: "HELPING", label: "Yes, treatment is helping" },
      { value: "PARTLY_HELPING", label: "Partly helping" },
      { value: "NOT_HELPING", label: "Not helping" },
      { value: "MAKING_WORSE", label: "Treatment causes problems or side effects" },
      { value: "NO_CURRENT_TREATMENT", label: "No current treatment" },
      { value: "UNSURE", label: "Unsure" },
    ],
    safetyNote:
      "Do not start, stop or change treatment based on this app. Speak with a doctor, pharmacist or qualified clinician.",
  },
  {
    id: "str_treatment_response_details",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "treatment_response_details",
    questionText: "What happens when you receive treatment or support?",
    helperText:
      "Describe what improves, what does not improve, how long benefits last, and whether treatment has limits.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 50,
    evidenceCategory: "TREATMENT",
    summaryLabel: "Treatment response details",
    safetyNote:
      "Treatment concerns should be discussed with a doctor, pharmacist or qualified clinician.",
  },
  {
    id: "str_treatment_changes",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "treatment_changes",
    questionText: "Has treatment changed over time?",
    helperText:
      "Examples include increased medication, new referrals, changed therapy, more frequent appointments, or stopped treatment.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 60,
    evidenceCategory: "TREATMENT",
    summaryLabel: "Treatment changes",
    options: yesNoUnsureOptions,
    safetyNote:
      "Do not start, stop or change treatment based on this app. Speak with a doctor, pharmacist or qualified clinician.",
  },
  {
    id: "str_treatment_change_details",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "treatment_change_details",
    questionText: "If treatment has changed, what changed and why?",
    helperText:
      "This may help identify useful medical records, referrals, medication changes, specialist reviews or treatment plans.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 70,
    evidenceCategory: "TREATMENT",
    summaryLabel: "Treatment change details",
    safetyNote:
      "Treatment concerns should be discussed with a doctor, pharmacist or qualified clinician.",
  },
  {
    id: "str_condition_maximum_improvement",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "condition_maximum_improvement",
    questionText: "Has a doctor told you the condition is stable or unlikely to improve much more?",
    helperText:
      "Only record what you have been told. This app does not decide whether a condition is stable or permanent.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 80,
    evidenceCategory: "STABILITY",
    summaryLabel: "Doctor comments about stability",
    options: yesNoUnsureOptions,
    safetyNote:
      "This app does not make medical findings about stability, permanence or maximum improvement.",
  },
  {
    id: "str_stability_evidence_available",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "stability_evidence_available",
    questionText: "What evidence shows the current stability or treatment response?",
    helperText:
      "Examples include GP notes, specialist reports, treatment plans, medication history, allied health notes, progress notes or review letters.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 90,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Stability and treatment evidence",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "str_stability_questions_for_doctor",
    groupKey: "STABILITY_TREATMENT_RESPONSE",
    questionKey: "stability_questions_for_doctor",
    questionText: "What questions should you ask your doctor about stability or treatment response?",
    helperText:
      "Write down anything you want to clarify at the next appointment.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 100,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Doctor questions about stability or treatment",
    safetyNote: garpMQuestionSafetyBoundary,
  },
];