import {
  GarpMQuestionTemplate,
  garpMQuestionSafetyBoundary,
  yesNoUnsureOptions,
} from "@/lib/garpM/questionTemplateModel";

export const worseningPreviousCompensationQuestions: GarpMQuestionTemplate[] = [
  {
    id: "wpc_previously_accepted",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "previously_accepted",
    questionText: "Has DVA previously accepted this condition?",
    helperText:
      "Only record what you know from DVA letters or previous decisions. Choose unsure if you are not certain.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 10,
    evidenceCategory: "PREVIOUS_COMPENSATION",
    summaryLabel: "Previously accepted by DVA",
    options: yesNoUnsureOptions,
    safetyNote:
      "This app does not confirm whether DVA has accepted a condition. Use DVA decision letters or professional advice where needed.",
  },
  {
    id: "wpc_original_act",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "original_act",
    questionText: "Which Act was the condition previously accepted or assessed under, if known?",
    helperText:
      "Examples include MRCA, DRCA or VEA. Choose unsure if you do not know.",
    answerType: "SINGLE_SELECT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 20,
    evidenceCategory: "PREVIOUS_COMPENSATION",
    summaryLabel: "Original Act",
    options: [
      { value: "MRCA", label: "MRCA" },
      { value: "DRCA", label: "DRCA" },
      { value: "VEA", label: "VEA" },
      { value: "MULTIPLE_OR_UNCLEAR", label: "Multiple or unclear" },
      { value: "UNSURE", label: "Unsure" },
    ],
    safetyNote:
      "This app does not decide which Act applies. Check DVA letters or speak with an advocate, lawyer or qualified support person.",
  },
  {
    id: "wpc_previous_compensation",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "previous_compensation",
    questionText: "Have you previously received compensation or assessment outcomes for this condition?",
    helperText:
      "This may include previous PI, DCP, incapacity, review or assessment material. Choose unsure if you are not certain.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 30,
    evidenceCategory: "PREVIOUS_COMPENSATION",
    summaryLabel: "Previous compensation or assessment",
    options: yesNoUnsureOptions,
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_decision_letter_available",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "decision_letter_available",
    questionText: "Do you have the previous DVA decision letter?",
    helperText:
      "Decision letters can help confirm dates, accepted conditions, Act details and what was previously decided.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 40,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Previous DVA decision letter available",
    options: yesNoUnsureOptions,
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_assessment_letter_available",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "assessment_letter_available",
    questionText: "Do you have any previous PI, DCP or assessment letter for this condition?",
    helperText:
      "Assessment material can help organise what has changed since the previous assessment.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 50,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Previous assessment material available",
    options: yesNoUnsureOptions,
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_previous_decision_date",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "previous_decision_date",
    questionText: "What was the date of the previous DVA decision, if known?",
    helperText:
      "Leave blank if you do not know. The exact date can be checked later from DVA letters.",
    answerType: "DATE",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 60,
    evidenceCategory: "PREVIOUS_COMPENSATION",
    summaryLabel: "Previous decision date",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_previous_assessment_date",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "previous_assessment_date",
    questionText: "What was the date of the previous assessment, if known?",
    helperText:
      "Leave blank if you do not know. The exact date can be checked later from assessment material.",
    answerType: "DATE",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 70,
    evidenceCategory: "PREVIOUS_COMPENSATION",
    summaryLabel: "Previous assessment date",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_worsening_claimed",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "worsening_claimed",
    questionText: "Are you preparing information because this condition may have worsened?",
    helperText:
      "Choose the closest answer. This does not decide whether DVA will accept worsening.",
    answerType: "YES_NO_UNSURE",
    requirementLevel: "REQUIRED",
    scope: "CONDITION",
    displayOrder: 80,
    evidenceCategory: "WORSENING",
    summaryLabel: "Worsening claimed or being considered",
    options: yesNoUnsureOptions,
    safetyNote:
      "This app does not decide whether a condition has worsened for DVA purposes. It only helps organise user-provided information.",
  },
  {
    id: "wpc_worsening_summary",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "worsening_summary",
    questionText: "What has worsened or changed since the previous decision or assessment?",
    helperText:
      "Describe changes in symptoms, treatment, stability, functional impact, lifestyle impact, work impact, medication, support needs or flare-ups.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 90,
    evidenceCategory: "WORSENING",
    summaryLabel: "Worsening summary",
    validationRules: [
      {
        type: "MIN_LENGTH",
        value: 10,
        message: "Add at least one plain-English example of what has changed.",
      },
    ],
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_worsening_timeline",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "worsening_timeline",
    questionText: "When did you first notice the worsening or change?",
    helperText:
      "Use approximate timing if needed, such as a month, year, event, treatment change or period of worsening.",
    answerType: "TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 100,
    evidenceCategory: "WORSENING",
    summaryLabel: "Worsening timeline",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_worsening_evidence",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "worsening_evidence",
    questionText: "What evidence may show the worsening or change?",
    helperText:
      "Examples include updated GP notes, specialist reports, treatment changes, medication changes, imaging, hearing tests, leave records, support letters or personal notes.",
    answerType: "LONG_TEXT",
    requirementLevel: "RECOMMENDED",
    scope: "CONDITION",
    displayOrder: 110,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Worsening evidence",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_missing_previous_documents",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "missing_previous_documents",
    questionText: "What previous DVA or assessment documents may still be missing?",
    helperText:
      "List anything you may need to locate, request or discuss with an advocate, lawyer or support person.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 120,
    evidenceCategory: "EVIDENCE_GAP",
    summaryLabel: "Missing previous decision or assessment documents",
    safetyNote: garpMQuestionSafetyBoundary,
  },
  {
    id: "wpc_questions_for_support",
    groupKey: "WORSENING_PREVIOUS_COMPENSATION",
    questionKey: "questions_for_support",
    questionText: "What questions should you ask an advocate, lawyer, doctor or support person about previous compensation or worsening?",
    helperText:
      "Write down questions about previous decisions, missing letters, updated evidence, worsening history or appointment preparation.",
    answerType: "LONG_TEXT",
    requirementLevel: "OPTIONAL",
    scope: "CONDITION",
    displayOrder: 130,
    evidenceCategory: "APPOINTMENT_PREP",
    summaryLabel: "Questions about previous compensation or worsening",
    safetyNote: garpMQuestionSafetyBoundary,
  },
];